[env]
platform = espressif32
framework = espidf
board = esp32dev
monitor_speed = 115200

[platformio]
default_envs = esp32_board1, esp32_board2

[env:esp32_board1]
upload_port = /dev/cu.usbserial-1120

[env:esp32_board2]
upload_port = /dev/cu.usbserial-1110
